# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:slim

pipelines:
  default:
    - step:          # non-parallel step
        name: Install npm modules
        script:
          - npm install
    - parallel:      # these 2 steps will run in parallel
        - step:
            name: Install surge.sh
            script:
              - npm install -g surge
        - step:
            name: build application
            script:
              - npm run build
    - step:          # non-parallel step
        name: Deploy to Surge
        script:         
          - surge --project ./build --domain fpn.surge.sh          