image: node:7.5.0

pipelines:
  default:
    - step:
        name: Build and push to S3
        script:
        - npm install -g surge
        - npm install
        - npm run build    
    - step:
        name: Deploy to test
        deployment: test
        script:
        - surge build fpn.surge.sh