# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:slim

pipelines:
  default:
      - step:
          name: install npm modules & build application
          script:
            - npm install
            - unset CI
            - npm run build
      - step:
          name: install surge.sh & deploy
          script:
            - npm install -g surge 
            - surge --project ./build --domain fpn.surge.sh