image: node:7.5.0

pipelines:
  default:
    - step:
        name: Build and push surge
        deployment: test
        script:
        - npm install -g surge
        - npm install
        - npm run build
        - surge build fpn.surge.sh
       