export default
    [
        {
            "id": 957,
            "regNum": "3343",
            "updateDate": "2018-08-16T15:36:27",
            "prtId": 169,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых инструментов \"Алёнка - Капитал\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"Алёнка – Капитал\"",
            "type": 1,
            "pageName": "ak",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d957&utm_agent=",
            "dataDate": "2018-09-11",
            "navOne": 4759.15,
            "navAll": 85433079.49,
            "period": 10,
            "incomeOne": -4.79,
            "navOnePrev": 4773.91,
            "navAllPrev": 85877424.89,
            "dailyIncomeOne": -0.31,
            "minInvestSum": 10000,
            "minReInvestSum": 5000,
            "formationDate": "2017-10-27",
            "companyShortName": "ООО \"УК \"Инвест Менеджмент Центр\"",
            "companyName": "Общество с ограниченной ответственностью \"Управляющая компания \"Инвест Менеджмент Центр\"",
            "logoURL": "site/org_169_logo.jpg",
        },
        {
            "id": 959,
            "regNum": "3374",
            "updateDate": "2018-08-16T15:07:12",
            "prtId": 169,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых инструментов \"Валютный резерв\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"Валютный резерв\"",
            "type": 1,
            "pageName": "vz",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d959&utm_agent=",
            "dataDate": "2018-09-11",
            "navOne": 1175.08,
            "navAll": 28249031.57,
            "period": 8,
            "incomeOne": 17.54,
            "navOnePrev": 1155,
            "navAllPrev": 27766108.92,
            "dailyIncomeOne": 1.74,
            "minInvestSum": 10000,
            "minReInvestSum": 5000,
            "formationDate": "2017-12-14",
            "companyShortName": "ООО \"УК \"Инвест Менеджмент Центр\"",
            "companyName": "Общество с ограниченной ответственностью \"Управляющая компания \"Инвест Менеджмент Центр\"",
            "logoURL": "site/org_169_logo.jpg"
        },
        {
            "id": 1110,
            "regNum": "0174-71670299",
            "updateDate": "2018-08-30T16:52:34",
            "prtId": 484,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых инструментов \"ТФГ - Валютные еврооблигации\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"ТФГ - Валютные еврооблигации\"",
            "type": 1,
            "pageName": "opif-rfi-tfg-valutnye-evroobligacii",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1110&utm_agent=",
            "dataDate": "2018-09-11",
            "navOne": 188.13,
            "navAll": 479307191.16,
            "period": 12,
            "incomeOne": 21.24,
            "navOnePrev": 185.91,
            "navAllPrev": 473635322.84,
            "dailyIncomeOne": 1.19,
            "minInvestSum": 300000,
            "minReInvestSum": 300000,
            "formationDate": "2004-02-20",
            "companyShortName": "АО \"УК ТФГ\"",
            "companyName": "Акционерное общество \"Управляющая компания \"ТРАНСФИНГРУП\"",
            "logoURL": "site/org_484_logo.jpg"
        },
        {
            "id": 1213,
            "regNum": "0364-75409132",
            "updateDate": "2018-09-12T09:58:04",
            "prtId": 291,
            "name": "открытый паевой инвестиционный фонд рыночных финансовых инструментов \"Арсагера - фонд смешанных инвестиций\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"Арсагера - СИ\"",
            "type": 1,
            "pageName": "fond_smeshannyh_investicij",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1213&utm_agent=",
            "dataDate": "2018-09-10",
            "navOne": 4743.48,
            "navAll": 140965211.29,
            "period": 12,
            "incomeOne": 4.67,
            "navOnePrev": 4757.97,
            "navAllPrev": 141395821.44,
            "dailyIncomeOne": -0.3,
            "minInvestSum": 1000,
            "minReInvestSum": 1000,
            "companyShortName": "ПАО \"УК \"Арсагера\"",
            "companyName": "публичное акционерное общество \"Управляющая компания \"Арсагера\"",
            "logoURL": "site/org_291_logo.jpg"
        },
        {
            "id": 1294,
            "regNum": "2116-94173014",
            "updateDate": "2018-09-04T12:49:22",
            "prtId": 278,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых инструментов \"Солид Перспективный\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"Солид Перспективный\"",
            "type": 1,
            "pageName": "solid-perspektivniy",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1294&utm_agent=",
            "dataDate": "2018-09-10",
            "navOne": 1916.58,
            "navAll": 8721986.44,
            "period": 12,
            "incomeOne": 22.84,
            "navOnePrev": 1898.29,
            "navAllPrev": 8638763.08,
            "dailyIncomeOne": 0.96,
            "minInvestSum": 1000,
            "minReInvestSum": 1000,
            "companyShortName": "АО \"СОЛИД Менеджмент\"",
            "companyName": "Акционерное общество \"СОЛИД Менеджмент\"",
            "logoURL": "site/org_278_logo.jpg"
        },
        {
            "id": 994,
            "regNum": "0626-94123756",
            "updateDate": "2018-08-30T16:53:54",
            "prtId": 484,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых инструментов \"ТФГ - Рублевые облигации\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"ТФГ - Рублевые облигации\"",
            "type": 1,
            "pageName": "opif-rfi-tfg-rublevye-obligacii",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d994&utm_agent=",
            "dataDate": "2018-09-11",
            "navOne": 294.84,
            "navAll": 2729278375.74,
            "period": 12,
            "incomeOne": 5.42,
            "navOnePrev": 294.81,
            "navAllPrev": 2728933814.15,
            "dailyIncomeOne": 0.01,
            "minInvestSum": 300000,
            "minReInvestSum": 300000,
            "formationDate": "2007-01-23",
            "companyShortName": "АО \"УК ТФГ\"",
            "companyName": "Акционерное общество \"Управляющая компания \"ТРАНСФИНГРУП\"",
            "logoURL": "site/org_484_logo.jpg"
        },
        {
            "id": 1138,
            "regNum": "0040-52697973",
            "updateDate": "2018-09-10T18:20:06",
            "prtId": 278,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых инструментов \"Солид-Инвест\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"Солид-Инвест\"",
            "type": 1,
            "pageName": "solid-invest",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1138&utm_agent=",
            "dataDate": "2018-09-10",
            "navOne": 465.66,
            "navAll": 119361972.39,
            "period": 12,
            "incomeOne": 31.76,
            "navOnePrev": 463.59,
            "navAllPrev": 118892996.4,
            "dailyIncomeOne": 0.45,
            "minInvestSum": 10000,
            "minReInvestSum": 1000,
            "companyShortName": "АО \"СОЛИД Менеджмент\"",
            "companyName": "Акционерное общество \"СОЛИД Менеджмент\"",
            "logoURL": "site/org_278_logo.jpg"
        },
        {
            "id": 1214,
            "regNum": "0363-75409054",
            "updateDate": "2018-09-12T09:56:23",
            "prtId": 291,
            "name": "открытый паевой инвестиционный фонд рыночных финансовых инструментов \"Арсагера - фонд акций\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"Арсагера - ФА\"",
            "type": 1,
            "pageName": "fond_akcij",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1214&utm_agent=",
            "dataDate": "2018-09-10",
            "navOne": 6776.09,
            "navAll": 439126788.55,
            "period": 12,
            "incomeOne": 4.08,
            "navOnePrev": 6796.49,
            "navAllPrev": 436660228.68,
            "dailyIncomeOne": -0.3,
            "minInvestSum": 1000,
            "minReInvestSum": 1000,
            "companyShortName": "ПАО \"УК \"Арсагера\"",
            "companyName": "публичное акционерное общество \"Управляющая компания \"Арсагера\"",
            "logoURL": "site/org_291_logo.jpg"
        },
        {
            "id": 1210,
            "regNum": "0351-76578546",
            "updateDate": "2018-09-04T12:48:18",
            "prtId": 278,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых инструментов \"Солид - Индекс МосБиржи\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"Солид - Индекс МосБиржи\"",
            "type": 1,
            "pageName": "solid-mmvb",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1210&utm_agent=",
            "dataDate": "2018-09-10",
            "navOne": 255161.89,
            "navAll": 79507731.95,
            "period": 12,
            "incomeOne": 26.17,
            "navOnePrev": 254280.36,
            "navAllPrev": 79233047.53,
            "dailyIncomeOne": 0.35,
            "minInvestSum": 10000,
            "minReInvestSum": 1000,
            "companyShortName": "АО \"СОЛИД Менеджмент\"",
            "companyName": "Акционерное общество \"СОЛИД Менеджмент\"",
            "logoURL": "site/org_278_logo.jpg"
        },
        {
            "id": 1245,
            "regNum": "3247",
            "updateDate": "2018-08-30T16:49:47",
            "prtId": 484,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых инструментов \"ТФГ - Российские акции\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"ТФГ - Российские акции\"",
            "type": 1,
            "pageName": "opif-rfi-tfg-rossiyskie-aktsii",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1245&utm_agent=",
            "dataDate": "2018-09-10",
            "navOne": 377.83,
            "navAll": 1163026473.74,
            "period": 12,
            "incomeOne": -99.88,
            "navOnePrev": 376.44,
            "navAllPrev": 1158742613.15,
            "dailyIncomeOne": 0.37,
            "minInvestSum": 300000,
            "minReInvestSum": 300000,
            "companyShortName": "АО \"УК ТФГ\"",
            "companyName": "Акционерное общество \"Управляющая компания \"ТРАНСФИНГРУП\"",
            "logoURL": "site/org_484_logo.jpg"
        },
        {
            "id": 1252,
            "regNum": "2721",
            "updateDate": "2018-09-12T10:00:17",
            "prtId": 291,
            "name": "открытый паевой инвестиционный фонд рыночных финансовых инструментов \"Арсагера - фонд облигаций КР 1.55\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"Арсагера - КР 1.55\"",
            "type": 1,
            "pageName": "fond_obligacij_kr_155",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1252&utm_agent=",
            "dataDate": "2018-09-10",
            "navOne": 1534.96,
            "navAll": 60209436.28,
            "period": 12,
            "incomeOne": 3.24,
            "navOnePrev": 1540.15,
            "navAllPrev": 64535778.01,
            "dailyIncomeOne": -0.34,
            "minInvestSum": 1000,
            "minReInvestSum": 1000,
            "formationDate": "2014-01-30",
            "companyShortName": "ПАО \"УК \"Арсагера\"",
            "companyName": "публичное акционерное общество \"Управляющая компания \"Арсагера\"",
            "logoURL": "site/org_291_logo.jpg"
        },
        {
            "id": 1220,
            "regNum": "0439-75408664",
            "updateDate": "2018-09-04T09:27:47",
            "prtId": 291,
            "name": "Интервальный паевой инвестиционный фонд акций \"Арсагера - акции 6.4\"",
            "shortName": "ИПИФА \"Арсагера-акции 6.4\"",
            "type": 2,
            "pageName": "akcii_64",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1220&utm_agent=",
            "dataDate": "2018-08-31",
            "navOne": 5492.38,
            "navAll": 372780560.34,
            "period": 12,
            "incomeOne": -0.44,
            "navOnePrev": 5721.53,
            "navAllPrev": 388333178.43,
            "dailyIncomeOne": -4.01,
            "minInvestSum": 1000,
            "minReInvestSum": 1000,
            "companyShortName": "ПАО \"УК \"Арсагера\"",
            "companyName": "публичное акционерное общество \"Управляющая компания \"Арсагера\"",
            "logoURL": "site/org_291_logo.jpg"
        },
        {
            "id": 1295,
            "regNum": "1903-94169099",
            "updateDate": "2018-09-12T10:04:56",
            "prtId": 278,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых инструментов \"Солид – Глобус\"",
            "shortName": "ОПИФ рыночных финансовых инструментов \"Солид – Глобус\"",
            "type": 1,
            "pageName": "solid-globus",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1295&utm_agent=",
            "dataDate": "2018-09-10",
            "navOne": 3281.81,
            "navAll": 39288100.41,
            "period": 12,
            "incomeOne": 25.48,
            "navOnePrev": 3243.64,
            "navAllPrev": 38831245.03,
            "dailyIncomeOne": 1.18,
            "minInvestSum": 10000,
            "minReInvestSum": 1000,
            "companyShortName": "АО \"СОЛИД Менеджмент\"",
            "companyName": "Акционерное общество \"СОЛИД Менеджмент\"",
            "logoURL": "site/org_278_logo.jpg"
        },
        {
            "id": 1251,
            "regNum": "3152",
            "updateDate": "2018-09-04T09:29:37",
            "prtId": 291,
            "name": "Интервальный паевой инвестиционный фонд рыночных финансовых инструментов \"Арсагера - акции Мира\"",
            "shortName": "ИПИФ рыночных финансовых инструментов \"Арсагера - АМ\"",
            "type": 2,
            "pageName": "akcii_mira",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1251&utm_agent=",
            "dataDate": "2018-08-31",
            "navOne": 1318.87,
            "navAll": 49349219.87,
            "period": 12,
            "incomeOne": 21.84,
            "navOnePrev": 1229.45,
            "navAllPrev": 46003104.05,
            "dailyIncomeOne": 7.27,
            "minInvestSum": 1000,
            "minReInvestSum": 1000,
            "companyShortName": "ПАО \"УК \"Арсагера\"",
            "companyName": "публичное акционерное общество \"Управляющая компания \"Арсагера\"",
            "logoURL": "site/org_291_logo.jpg"
        },
        {
            "id": 1301,
            "regNum": "0065-58549452",
            "updateDate": "2018-09-04T12:46:21",
            "prtId": 278,
            "name": "Открытый паевой инвестиционный фонд рыночных финансовых  инструментов \"Фонд долгосрочных инвестиций Солид\"",
            "shortName": "ОПИФ рыночных финансовых  инструментов \"ФДИ Солид\"",
            "type": 1,
            "pageName": "fdi-solid",
            "buyOnlineURL": "https://my.platform.finance/utm_redirect?utm_url=main%3fsysname%3dbidbuy_edit%26prodid%3d1301&utm_agent=",
            "dataDate": "2018-09-10",
            "navOne": 2090.9,
            "navAll": 38345200.06,
            "period": 12,
            "incomeOne": 5.11,
            "navOnePrev": 2089.64,
            "navAllPrev": 38322000.16,
            "dailyIncomeOne": 0.06,
            "minInvestSum": 10000,
            "minReInvestSum": 1000,
            "companyShortName": "АО \"СОЛИД Менеджмент\"",
            "companyName": "Акционерное общество \"СОЛИД Менеджмент\"",
            "logoURL": "site/org_278_logo.jpg"
        },
        {
            "id": 1133,
            "regNum": "0045-54859434",
            "updateDate": "2018-09-04T12:47:15",
            "prtId": 278,
            "name": "Интервальный паевой инвестиционный фонд рыночных финансовых  инструментов \"Солид Интервальный\"",
            "shortName": "ИПИФ рыночных финансовых  инструментов \"Солид Интервальный\"",
            "type": 2,
            "pageName": "solid-intervalniy",
            "buyOnlineURL": "none",
            "dataDate": "2018-08-31",
            "navOne": 60.01,
            "navAll": 44985099.14,
            "period": 12,
            "incomeOne": 4.01,
            "navOnePrev": 61.2,
            "navAllPrev": 46608481.02,
            "dailyIncomeOne": -1.94,
            "minInvestSum": 10000,
            "minReInvestSum": 1000,
            "companyShortName": "АО \"СОЛИД Менеджмент\"",
            "companyName": "Акционерное общество \"СОЛИД Менеджмент\"",
            "logoURL": "site/org_278_logo.jpg",
            "nextPeriodStartDate": "2018-10-18"
        }
    ]